baseURL: "https://sidlibrary.org/"
defaultContentLanguage: en

enableRobotsTXT: true
paginate: 10
summaryLength: 0

outputs:
  home:
    - html
    - rss
    - json

theme: "PaperMod"
_merge: shallow

params:
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  author: Sidney Jeong
      
  titleCaseStyle: chicago

  defaultTheme: dark
  disableThemeToggle: false
  
  homeInfoParams:
    Title: "&#129504; We must think! But what we must?"
    Content: Hello there! I'm Sidney Jeong, a neurodivergent queer tech worker who decided to leave academic world of social science years ago for this new journey.
    
  profileMode:
    enabled: true
    title: |
      We must think! But what we must?
    subtitle: |
      Hello there! I'm Sidney Jeong, a neurodivergent queer tech worker who decided to leave the world of academia in social science many years ago for this new journey of career and life.

      <span style="font-size: 12px; font-style: italic;">Please note that the blog is going under an overhaul. I'll try to fill the contents back soon.</span>
    imageUrl: "logo.png"
    imageTitle: The logo of this blog. It is an imaginary coat of arms of the Republic of Dreamcatcher.

  socialIcons:
    - name: email
      url: "mailto:jeong.sid@sidlibrary.org"
    - name: linkedin
      url: "https://www.linkedin.com/in/sidney-jeong-56b52449/"
    - name: github
      url: "https://github.com/sid0831"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 
    keys: ["title", "permalink", "summary", "content"]

  pygmentsUseClasses: true

  assets:
    disableHLJS: true

languages:
  en:
    languageCode: en
    languageName: English
    languageDirection: ltr
    weight: 1

    title: "The Discouraged Revolutionary's Hidden Den"

    params:
      dateFormat: "2 January 2006"
      description: "The den for evidence-based revolution"
    
    menu:
      main:
        - identifier: home
          name: Home
          pageRef: /
          weight: 1
        - identifier: blog
          name: Blog
          pageRef: /blog/
          weight: 10
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: about-me
          name: About Me
          url: /about-me/
          weight: 40
