site_name: pie.dc.sidlibrary.org
theme:
  name: material
  font:
    text: Vollkorn
    code: Roboto Mono
  logo: assets/Dreamcatcher_SSR_icon.png
  favicon: assets/Dreamcatcher_SSR_icon.png
  features:
    - navigation.indexes
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sid0831
      name: My GitHub Repository
copyright: "&copy; 2022 Sidney Jeong, BSD 3-Clause."
extra_css:
  - stylesheets/extra.css